<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 04:12+0000
// PO revision date:  2013-03-06 04:24+0000
$lang = array(
	'category_color' => array(
		'length' => 'ប្រឡោះពណ៌តម្រូវ​ឲ្យមានយ៉ាងតិច6តួ',
		'required' => 'ប្រឡោះពណ៌តម្រូវឲ្យមាន',
	) ,
	'category_description' => array(
		'required' => 'ប្រឡោះពិពណ៌នាតម្រូវឲ្យមាន',
	) ,
	'category_image' => array(
		'type' => 'ប្រឡោះរូបភាពហាក់ដូចអត់មានអី។​ អនុញ្ញាត្តិតែទំរង់ JPG PNG និង GIF',
		'valid' => 'ប្រឡោះអ៊ីម៉ែលហាក់ដូចអត់មានអី',
	) ,
	'category_title' => array(
		'length' => 'ប្រឡោះបែបបទតម្រូវឲ្យមានយ៉ាងតិច 3 និងមិនច្រើនជាង 80តួ',
		'required' => 'ប្រឡោះអ៊ីម៉ែលតម្រូវឲ្យមាន',
	) ,
	'parent_id' => array(
		'exists' => 'ប្រភេទមេមិនមាន',
		'numeric' => 'ប្រភេទមេត្រូវតែជាលេខ',
		'required' => 'ប្រភេទមេតម្រូវឲ្យមាន',
		'same' => 'ប្រភេទនិងប្រភេទមេមិនអាចដូចគ្នា',
		'special' => 'ប្រភេទពិសេសមិនអាចជាកូនប្រភេទ',
	) ,
);
