<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 04:12+0000
// PO revision date:  2013-03-06 04:52+0000
$lang = array(
	'database_name' => 'ឈ្មោះ Database',
	'disable' => 'លាក់',
	'enable' => 'បង្ហាញ',
	'finished' => 'រួចរាល់',
	'general' => 'ទូទៅ',
	'go_back' => 'ត្រលប់ក្រោយ',
	'map' => 'ផែនទី',
	'other_steps' => 'ជំហានដទៃ',
	'password' => 'ពាក្យសំងាត់',
	'password_description' => 'ពាក្យសំងាត់ Database របស់អ្នក',
	'previous' => 'ក្រោយ',
	'site_email' => 'អាស័យដ្ឋានអ៊ីម៉ែលគេហទំព័រ',
	'site_name' => 'នាមគេហទំព័រ',
	'site_name_description' => 'ឈ្មោះគេហទំព័រអ្នក',
);
