<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2013-03-11 04:12+0000
// PO revision date:  2013-03-07 07:54+0000
$lang = array(
	'date' => 'កាលបរិច្ឆេទ​ចូល',
	'date_added' => 'បាន​បន្ថែម​កាលបរិច្ឆេទ',
	'last_access' => 'ចូល​ដំណើរការ​ចុងក្រោយ',
	'sharing_color' => array(
		'length' => 'វាល​ពណ៌​ត្រូវតែ​មាន៦តួអក្សរ។',
		'required' => 'បាន​ទាមទារ​វាល​ពណ៌។',
	) ,
	'sharing_name' => array(
		'length' => 'ឈ្មោះ​ចែករំលែក​ហាក់​បង្ហាញ​ថា​មិន​ត្រឹមត្រូវ។',
		'required' => 'បាន​ទាមទារ​ឈ្មោះ​ចែករំលែក។',
	) ,
	'sharing_url' => array(
		'exists' => 'URL របស់​តំបន់​បណ្ដាញ​គឺ​មាន​រួចហើយ។',
		'length' => 'URL របស់​តំបន់​បណ្ដាញ​ហាក់​បង្ហាញ​ថា​មិន​ត្រឹមត្រូវ។',
		'required' => 'បាន​ទាមទារ URL របស់​តំបន់​បណ្ដាញ។',
	) ,
);
